name: Branch convention
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  build:
    # Job name is Greeting
    name: Check
    # This job runs on Linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: deepakputhraya/action-branch-name@test
        with:
          regex: '([a-z])+\/([a-z])+'
          allowed_prefixes: 'feature,stable,fix'
          ignore: master,develop
          min_length: 5
          max_length: 20
